
"""Geodykes Web Service.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from typing import TYPE_CHECKING, Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr


if TYPE_CHECKING:
    from datetime import datetime


class Reading(BaseModel):
    """Reading."""

    id: StrictInt
    crossection: StrictStr
    sensor_id: StrictInt
    sensor_name: StrictStr
    sensor_type: StrictStr
    sensor_location: list[StrictFloat | StrictInt]
    sensor_is_active: StrictBool
    location_in_topology: list[StrictFloat | StrictInt]
    unit: StrictStr
    value: StrictFloat | StrictInt
    time: datetime
    __properties: ClassVar[list[str]] = ["id", "crossection", "sensor_id", "sensor_name", "sensor_type", "sensor_location", "sensor_is_active", "location_in_topology", "unit", "value", "time"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias."""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias."""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Reading from a JSON string."""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set()

        return self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Reading from a dict."""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        return cls.model_validate({
            "id": obj.get("id"),
            "crossection": obj.get("crossection"),
            "sensor_id": obj.get("sensor_id"),
            "sensor_name": obj.get("sensor_name"),
            "sensor_type": obj.get("sensor_type"),
            "sensor_location": obj.get("sensor_location"),
            "sensor_is_active": obj.get("sensor_is_active"),
            "location_in_topology": obj.get("location_in_topology"),
            "unit": obj.get("unit"),
            "value": obj.get("value"),
            "time": obj.get("time"),
        })


