# coding: utf-8

"""
    Geodykes Web Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dykes import Dykes

class TestDykes(unittest.TestCase):
    """Dykes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dykes:
        """Test Dykes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dykes`
        """
        model = Dykes()
        if include_optional:
            return Dykes(
                items = [
                    openapi_client.models.dyke_schema.DykeSchema(
                        name = 'Duifpolder', 
                        description = '', )
                    ]
            )
        else:
            return Dykes(
                items = [
                    openapi_client.models.dyke_schema.DykeSchema(
                        name = 'Duifpolder', 
                        description = '', )
                    ],
        )
        """

    def testDykes(self):
        """Test Dykes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
