
"""Geodykes Web Service.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from openapi_client.models.deck import Deck


class TestDeck(unittest.TestCase):
    """Deck unit test stubs."""

    def setUp(self) -> None:
        pass

    def tearDown(self) -> None:
        pass

    def make_instance(self, include_optional) -> Deck:
        """Test Deck
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included.
        """
        # uncomment below to create an instance of `Deck`
        """
        model = Deck()
        if include_optional:
            return Deck(
                name = '',
                description = '',
                id = 56,
                cards = [
                    openapi_client.models.card.Card(
                        front = '',
                        back = '',
                        hint = '',
                        id = 56,
                        deck_id = 56, )
                    ]
            )
        else:
            return Deck(
                name = '',
                id = 56,
                cards = [
                    openapi_client.models.card.Card(
                        front = '',
                        back = '',
                        hint = '',
                        id = 56,
                        deck_id = 56, )
                    ],
        )
        """

    def testDeck(self) -> None:
        """Test Deck."""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == "__main__":
    unittest.main()
