# coding: utf-8

"""
    Geodykes Web Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.readings import Readings

class TestReadings(unittest.TestCase):
    """Readings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Readings:
        """Test Readings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Readings`
        """
        model = Readings()
        if include_optional:
            return Readings(
                readings = [
                    openapi_client.models.reading.Reading(
                        id = 56, 
                        crossection = '', 
                        sensor_id = 56, 
                        sensor_name = '', 
                        sensor_type = '', 
                        sensor_location = [
                            1.337
                            ], 
                        sensor_is_active = True, 
                        location_in_topology = [
                            1.337
                            ], 
                        unit = '', 
                        value = 1.337, 
                        time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return Readings(
                readings = [
                    openapi_client.models.reading.Reading(
                        id = 56, 
                        crossection = '', 
                        sensor_id = 56, 
                        sensor_name = '', 
                        sensor_type = '', 
                        sensor_location = [
                            1.337
                            ], 
                        sensor_is_active = True, 
                        location_in_topology = [
                            1.337
                            ], 
                        unit = '', 
                        value = 1.337, 
                        time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testReadings(self):
        """Test Readings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
