# coding: utf-8

"""
    Geodykes Web Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_cards_api_decks_deck_id_cards_post(self) -> None:
        """Test case for create_cards_api_decks_deck_id_cards_post

        Create Cards
        """
        pass

    def test_create_deck_api_decks_post(self) -> None:
        """Test case for create_deck_api_decks_post

        Create Deck
        """
        pass

    def test_create_reading_api_readings_post(self) -> None:
        """Test case for create_reading_api_readings_post

        Create Reading
        """
        pass

    def test_create_readings_api_readings_batch2_post(self) -> None:
        """Test case for create_readings_api_readings_batch2_post

        Create Readings
        """
        pass

    def test_create_readings_in_batch_api_readings_batch_post(self) -> None:
        """Test case for create_readings_in_batch_api_readings_batch_post

        Create Readings In Batch
        """
        pass

    def test_get_card_api_cards_card_id_get(self) -> None:
        """Test case for get_card_api_cards_card_id_get

        Get Card
        """
        pass

    def test_get_deck_api_decks_deck_id_get(self) -> None:
        """Test case for get_deck_api_decks_deck_id_get

        Get Deck
        """
        pass

    def test_get_dyke_api_dykes_dyke_id_get(self) -> None:
        """Test case for get_dyke_api_dykes_dyke_id_get

        Get Dyke
        """
        pass

    def test_list_cards_api_decks_deck_id_cards_get(self) -> None:
        """Test case for list_cards_api_decks_deck_id_cards_get

        List Cards
        """
        pass

    def test_list_decks_api_decks_get(self) -> None:
        """Test case for list_decks_api_decks_get

        List Decks
        """
        pass

    def test_list_dykes_api_dykes_get(self) -> None:
        """Test case for list_dykes_api_dykes_get

        List Dykes
        """
        pass

    def test_list_readings_api_readings_get(self) -> None:
        """Test case for list_readings_api_readings_get

        List Readings
        """
        pass

    def test_update_cards_api_decks_deck_id_cards_put(self) -> None:
        """Test case for update_cards_api_decks_deck_id_cards_put

        Update Cards
        """
        pass

    def test_update_deck_api_decks_deck_id_put(self) -> None:
        """Test case for update_deck_api_decks_deck_id_put

        Update Deck
        """
        pass


if __name__ == '__main__':
    unittest.main()
