# coding: utf-8

"""
    Geodykes Web Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.deck_create import DeckCreate

class TestDeckCreate(unittest.TestCase):
    """DeckCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeckCreate:
        """Test DeckCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeckCreate`
        """
        model = DeckCreate()
        if include_optional:
            return DeckCreate(
                name = '',
                description = ''
            )
        else:
            return DeckCreate(
                name = '',
        )
        """

    def testDeckCreate(self):
        """Test DeckCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
