"""Added sensors, readings and sensor types

Revision ID: 2a890c8d9042
Revises: 5cf0e65624b6
Create Date: 2024-07-22 16:09:04.564652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a890c8d9042'
down_revision = '5cf0e65624b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('multisensor', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topology',
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_of_measure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit')
    )
    op.create_table('location_in_topology',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('topology_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_unit_association',
    sa.Column('sensor_type_id', sa.Integer(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_type.id'], ),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measure.id'], ),
    sa.PrimaryKeyConstraint('sensor_type_id', 'unit_of_measure_id')
    )
    op.create_table('crossection_layer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crossection_id', sa.Integer(), nullable=False),
    sa.Column('top_topology_id', sa.Integer(), nullable=False),
    sa.Column('bottom_topology_id', sa.Integer(), nullable=False),
    sa.Column('soil_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bottom_topology_id'], ['topology.id'], ),
    sa.ForeignKeyConstraint(['crossection_id'], ['crossection.id'], ),
    sa.ForeignKeyConstraint(['top_topology_id'], ['topology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading',
    sa.Column('crossection_id', sa.Integer(), nullable=False),
    sa.Column('location_in_topology_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crossection_id'], ['crossection.id'], ),
    sa.ForeignKeyConstraint(['location_in_topology_id'], ['location_in_topology.id'], ),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_type.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sensor_type_id', sa.Integer(), nullable=False),
    sa.Column('location_in_topology_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_in_topology_id'], ['location_in_topology.id'], ),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('crossection_dyke_id_fkey', 'crossection', type_='foreignkey')
    op.create_foreign_key(None, 'crossection', 'dyke', ['dyke_id'], ['id'])
    op.drop_column('crossection', 'crossection_id')
    op.drop_column('dyke', 'dyke_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dyke', sa.Column('dyke_id', sa.INTEGER(), server_default=sa.text("nextval('dyke_dyke_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('crossection', sa.Column('crossection_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'crossection', type_='foreignkey')
    op.create_foreign_key('crossection_dyke_id_fkey', 'crossection', 'dyke', ['dyke_id'], ['dyke_id'])
    op.drop_table('sensor')
    op.drop_table('reading')
    op.drop_table('crossection_layer')
    op.drop_table('sensor_unit_association')
    op.drop_table('location_in_topology')
    op.drop_table('unit_of_measure')
    op.drop_table('topology')
    op.drop_table('sensor_type')
    # ### end Alembic commands ###
