"""Debugging Alembic

Revision ID: 7c5f710edb86
Revises: abb62721e019
Create Date: 2024-06-11 16:51:54.107321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5f710edb86'
down_revision = 'abb62721e019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dyke',
        sa.Column('dyke_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('dyke_id')
    )
    op.create_table('crossection',
        sa.Column('crossection_id', sa.Integer(), nullable=False),
        sa.Column('dyke_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('topology', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['dyke_id'], ['dyke.dyke_id']),
        sa.PrimaryKeyConstraint('crossection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crossection')
    op.drop_table('dyke')
    # ### end Alembic commands ###
