"""Added Crossection

Revision ID: f7c7ff779224
Revises: 5cf0e65624b6
Create Date: 2024-06-18 16:05:18.639420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c7ff779224'
down_revision = '5cf0e65624b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topology',
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crossection_layer',
    sa.Column('crossection_id', sa.Integer(), nullable=False),
    sa.Column('top_topology_id', sa.Integer(), nullable=False),
    sa.Column('bottom_topology_id', sa.Integer(), nullable=False),
    sa.Column('soil_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bottom_topology_id'], ['topology.id'], ),
    sa.ForeignKeyConstraint(['crossection_id'], ['crossection.id'], ),
    sa.ForeignKeyConstraint(['top_topology_id'], ['topology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('crossection_dyke_id_fkey', 'crossection', type_='foreignkey')
    op.create_foreign_key(None, 'crossection', 'dyke', ['dyke_id'], ['id'])
    op.drop_column('crossection', 'crossection_id')
    op.drop_column('dyke', 'dyke_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dyke', sa.Column('dyke_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('crossection', sa.Column('crossection_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'crossection', type_='foreignkey')
    op.create_foreign_key('crossection_dyke_id_fkey', 'crossection', 'dyke', ['dyke_id'], ['dyke_id'])
    op.drop_table('crossection_layer')
    op.drop_table('topology')
    # ### end Alembic commands ###
