# coding: utf-8

# flake8: noqa

"""
    Geodykes Web Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.card import Card
from openapi_client.models.card_create import CardCreate
from openapi_client.models.cards import Cards
from openapi_client.models.deck import Deck
from openapi_client.models.deck_create import DeckCreate
from openapi_client.models.decks import Decks
from openapi_client.models.dyke_schema import DykeSchema
from openapi_client.models.dykes import Dykes
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.reading import Reading
from openapi_client.models.readings import Readings
from openapi_client.models.validation_error import ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner
